apiVersion: apps/v1
kind: Deployment
metadata:
  name: swarm-visualizer
  labels:
    app: swarm-visualizer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swarm-visualizer
  template:
    metadata:
      labels:
        app: swarm-visualizer
    spec:
      containers:
        - name: swarm-visualizer
          image: sreejitharmorcode/webgoat:latest
          ports:
            - containerPort: 9090 # Port exposed by the visualizer
          env:
            - name: VISUALIZER_TASK
              value: "true" # Enable task visualization if needed
