apiVersion: v1
kind: Service
metadata:
  name: webgoat-service
spec:
  type: LoadBalancer # Use LoadBalancer to expose the service externally
  ports:
    - port: 80        # Port to access the service externally
      targetPort: 9090 # Port on which the visualizer is running inside the pod
  selector:
    app: webgoat # Matches the deployment's labels
